### ISSUE TITLE
Missing image on two reports.

### ISSUE THREAD

**Issue by jordanmack** [bbarton/personality_app#10]
<img width="429" alt="Screen Shot 2019-09-20 at 1 47 28 PM" src="https://user-images.githubusercontent.com/37931/65358120-a379bb80-dbad-11e9-84ba-684f7cc73e6f.png">

**Comment by bbarton** [comment]
The app isn't yet saving a copy of their Twitter image, it's just using Twitter's avatar URL. Will remedy this.

**Comment by bbarton** [comment]
The app now saves a copy of the image.
