### ISSUE TITLE
Reports have no dates.

### ISSUE THREAD

**Issue by jordanmack** [bbarton/personality_app#12]
Reports have no dates or metrics to imply that a report may be out of date, and should be run again.

**Comment by bbarton** [comment]
That's a good point. I'll add a list item to the "See what we analyzed" dropdown (there is one there but it's hidden behind a link) and will look for another place to display that info.

**Comment by bbarton** [comment]
Now shows date above nav:

![Screen Shot 2019-10-05 at 11 44 04 AM](https://user-images.githubusercontent.com/1076666/66259398-7a3c5c00-e765-11e9-973d-1debe33fc849.png)
