### ISSUE TITLE
Limit "Who's like you" section.

### ISSUE THREAD

**Issue by jordanmack** [bbarton/personality_app#4]
The "Who's like you" section shows too many profiles. Mine has 39 right now. 

![20190918120525](https://user-images.githubusercontent.com/37931/65177959-a1c4c200-da0c-11e9-914f-fe2d0065735b.png)

**Comment by bbarton** [comment]
Since this report was opened it's been capped at 8, with a "load more" button which loads the rest. Will eventually make it load chunks iteratively rather than all at once.
